[package]
name = "aleo-prover"
version = "0.4.5"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#snarkvm = { path = "../../src/snarkVM" }
#snarkvm-algorithms = { path = "../../src/snarkVM/algorithms" }
#snarkos = { path = "../../src/snarkOS" }
snarkvm = { git = "https://github.com/harukama/snarkVM.git", branch = "feat/snarkvm-cuda-tokio" }
snarkvm-algorithms = { git = "https://github.com/harukama/snarkVM.git", branch = "feat/snarkvm-cuda-tokio" }
#snarkvm = "0.9.6"
#snarkvm-algorithms = "0.9.6"
#snarkos-node-messages = { git = "https://github.com/AleoHQ/snarkOS.git", branch = "testnet3" }
snarkos-node-messages = { git = "https://github.com/harukama/snarkOS.git", branch = "testnet3-cuda" }
rand = "0.8.5"
num_cpus = "1.14.0"
rayon = "1.6.0"
anyhow = "1.0.66"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio-stream = "0.1.11"
futures = "0.3.25"
futures-util = "0.3.25"
crossbeam = "0.8.2"
bytes = "1.3.0"
bincode = "1.3.3"
byteorder = "1.4.3"
ansi_term = "0.12.1"
json-rpc-types = "1.2.0"
hex = "0.4.3"

#[dependencies.aleo-stratum]
#git = "https://github.com/HarukaMa/aleo-pool-server"
#branch = "testnet3-dummy"
#path = "../aleo-operator/stratum"

[dependencies.clap]
version = "4.0.28"
features = ["derive"]

[dependencies.tokio]
version = "1.22.0"
features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "net"
]

[dependencies.tokio-util]
version = "0.7.4"
features = ["codec"]

[dependencies.serde_json]
version = "1.0.89"
features = ["preserve_order"]

[features]
cuda = ["snarkvm/cuda"]

[profile.dev]
opt-level = 1
debug-assertions = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
